### ISSUE TITLE
What is this project about

### ISSUE THREAD

**Issue by carloskim123** [walteronoh/crypto-cross-language#1]
It seems interesting. I could add a couple more services once i understand how the app works

**Comment by walteronoh** [comment]
@carloskim123  Just add a framework of your choice, and implement hashing mechanism using crypto. 
Also, you should make sure that data transfer between the different frameworks is possible, ensuring the data is encrypted on transit.

**Comment by carloskim123** [comment]
I dont even understand what the project is supposed to do

**Comment by carloskim123** [comment]
I dont like using nest due to its architecture. I think plain node would be a good option cause it doesn't require service and module structure and data flow is easy to manage

**Comment by carloskim123** [comment]
You should check out this [stackoverflow post](https://stackoverflow.com/questions/6953286/how-to-encrypt-data-that-needs-to-be-decrypted-in-node-js)

**Comment by walteronoh** [comment]
You can implement it using ExpressJs. Create a new folder 'express-crypto'

**Comment by walteronoh** [comment]
> You should check out this [stackoverflow post](https://stackoverflow.com/questions/6953286/how-to-encrypt-data-that-needs-to-be-decrypted-in-node-js)

A good extract to refer to.

**Comment by carloskim123** [comment]
Add me as a contributor so I won't have to fork it
